name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - name: Random Name
        uses: pullreminders/label-when-approved-action@v1
